version: "3.8"

services:
    db:
        image: pocket-digest-db:latest
        container_name: pocketdigest_db
        build:
            context: ./db
        ports:
            - 54320:${POSTGRES_PORT}
        environment:
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - PGDATA=/pgdata
        volumes:
            - db-data:/var/lib/postgresql/data
        restart: always
        networks: 
            - deno
    pgadmin:
        image: dpage/pgadmin4
        container_name: pocketdigest_pgadmin
        depends_on:
            - db
        ports:
            - ${PGADMIN_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
            - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        restart: always
        networks: 
            - deno
    deno:
        image: pocket-digest-app:latest
        container_name: pocketdigest_app
        build: 
            context: .
            args:
                app_port: ${APP_PORT}
        depends_on:
            - db
        ports:
            - ${APP_PORT}:${APP_PORT}
        environment:
            - APP_ENV=production
        restart: always
        networks: 
            - deno
networks:
  deno: {}

volumes:
    db-data:
    pgadmin-data: